#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WilmaaRemote.Resource", IsApplication=true)]

namespace WilmaaRemote
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PullToRefresharp.Resource.Attribute.contentViewId = global::WilmaaRemote.Resource.Attribute.contentViewId;
			global::PullToRefresharp.Resource.Attribute.headerIconDrawable = global::WilmaaRemote.Resource.Attribute.headerIconDrawable;
			global::PullToRefresharp.Resource.Attribute.headerId = global::WilmaaRemote.Resource.Attribute.headerId;
			global::PullToRefresharp.Resource.Attribute.headerTextColor = global::WilmaaRemote.Resource.Attribute.headerTextColor;
			global::PullToRefresharp.Resource.Attribute.ptrHeaderBackground = global::WilmaaRemote.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresharp.Resource.Attribute.pullDownProgressIndicatorId = global::WilmaaRemote.Resource.Attribute.pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Attribute.pullDownTension = global::WilmaaRemote.Resource.Attribute.pullDownTension;
			global::PullToRefresharp.Resource.Attribute.pullEnabled = global::WilmaaRemote.Resource.Attribute.pullEnabled;
			global::PullToRefresharp.Resource.Attribute.pullToRefreshText = global::WilmaaRemote.Resource.Attribute.pullToRefreshText;
			global::PullToRefresharp.Resource.Attribute.refreshingText = global::WilmaaRemote.Resource.Attribute.refreshingText;
			global::PullToRefresharp.Resource.Attribute.releaseToRefreshText = global::WilmaaRemote.Resource.Attribute.releaseToRefreshText;
			global::PullToRefresharp.Resource.Attribute.snapbackDuration = global::WilmaaRemote.Resource.Attribute.snapbackDuration;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_end = global::WilmaaRemote.Resource.Color.ptrsharp_sb_gradient_end;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_start = global::WilmaaRemote.Resource.Color.ptrsharp_sb_gradient_start;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text = global::WilmaaRemote.Resource.Color.ptrsharp_sb_header_text;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = global::WilmaaRemote.Resource.Color.ptrsharp_sb_header_text_shadow;
			global::PullToRefresharp.Resource.Drawable.progress_medium_holo = global::WilmaaRemote.Resource.Drawable.progress_medium_holo;
			global::PullToRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = global::WilmaaRemote.Resource.Drawable.ptrsharp_serious_business_gradient;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow = global::WilmaaRemote.Resource.Drawable.serious_business_arrow;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow2 = global::WilmaaRemote.Resource.Drawable.serious_business_arrow2;
			global::PullToRefresharp.Resource.Drawable.spinner_20_inner_holo = global::WilmaaRemote.Resource.Drawable.spinner_20_inner_holo;
			global::PullToRefresharp.Resource.Drawable.spinner_20_outer_holo = global::WilmaaRemote.Resource.Drawable.spinner_20_outer_holo;
			global::PullToRefresharp.Resource.Id.header = global::WilmaaRemote.Resource.Id.header;
			global::PullToRefresharp.Resource.Id.header_container = global::WilmaaRemote.Resource.Id.header_container;
			global::PullToRefresharp.Resource.Id.icon = global::WilmaaRemote.Resource.Id.icon;
			global::PullToRefresharp.Resource.Id.pullDownProgressIndicator = global::WilmaaRemote.Resource.Id.pullDownProgressIndicator;
			global::PullToRefresharp.Resource.Id.text = global::WilmaaRemote.Resource.Id.text;
			global::PullToRefresharp.Resource.Layout.ptrsharp_header = global::WilmaaRemote.Resource.Layout.ptrsharp_header;
			global::PullToRefresharp.Resource.String.library_name = global::WilmaaRemote.Resource.String.library_name;
			global::PullToRefresharp.Resource.String.ptrsharp_pull_to_refresh = global::WilmaaRemote.Resource.String.ptrsharp_pull_to_refresh;
			global::PullToRefresharp.Resource.String.ptrsharp_refreshing = global::WilmaaRemote.Resource.String.ptrsharp_refreshing;
			global::PullToRefresharp.Resource.String.ptrsharp_release_to_refresh = global::WilmaaRemote.Resource.String.ptrsharp_release_to_refresh;
			global::PullToRefresharp.Resource.Style.HoloProgressMedium = global::WilmaaRemote.Resource.Style.HoloProgressMedium;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_contentViewId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerId = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_headerId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_headerTextColor;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_pullDownTension;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_pullEnabled;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_refreshingText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration = global::WilmaaRemote.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public const int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ptrsharp_sb_gradient_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ptrsharp_sb_gradient_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ptrsharp_sb_header_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ptrsharp_sb_header_text_shadow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ArrowDown = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int progress_medium_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ptrsharp_serious_business_gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int serious_business_arrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int serious_business_arrow2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int spinner_20_inner_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int spinner_20_outer_holo = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int btnSettings = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int buttonClose = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int buttonDown = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int buttonS = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int buttonUP = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int buttonVDown = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int buttonVMute = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int buttonVUp = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int frameLayout1 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int header = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int header_container = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int icon = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout2 = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout3 = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout4 = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout5 = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int pullDownProgressIndicator = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int relativeLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int text = 2131165203;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ptrsharp_header = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int app_name = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int hello = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ptrsharp_pull_to_refresh = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ptrsharp_refreshing = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ptrsharp_release_to_refresh = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int HoloProgressMedium = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresharpWrapper = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int PullToRefresharpWrapper_contentViewId = 1;
			
			// aapt resource value: 10
			public const int PullToRefresharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int PullToRefresharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int PullToRefresharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int PullToRefresharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int PullToRefresharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int PullToRefresharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int PullToRefresharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int PullToRefresharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int PullToRefresharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int PullToRefresharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int PullToRefresharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
